//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.CommonUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.CommonUtility.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category color deleted successfully..
        /// </summary>
        public static string CategoryColorDeleted {
            get {
                return ResourceManager.GetString("CategoryColorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category color created successfully..
        /// </summary>
        public static string CategoryColorSaved {
            get {
                return ResourceManager.GetString("CategoryColorSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category created successfully..
        /// </summary>
        public static string CategoryCreated {
            get {
                return ResourceManager.GetString("CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category deleted successfully..
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category already exists!.
        /// </summary>
        public static string CategoryExists {
            get {
                return ResourceManager.GetString("CategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category updated successfully..
        /// </summary>
        public static string CategoryUpdated {
            get {
                return ResourceManager.GetString("CategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color already exists!.
        /// </summary>
        public static string ColorExists {
            get {
                return ResourceManager.GetString("ColorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fetched successfully..
        /// </summary>
        public static string DataFetched {
            get {
                return ResourceManager.GetString("DataFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer deleted successfully..
        /// </summary>
        public static string DealerDeleted {
            get {
                return ResourceManager.GetString("DealerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer already exists. Please try with other username..
        /// </summary>
        public static string DealerExists {
            get {
                return ResourceManager.GetString("DealerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer saved successfully..
        /// </summary>
        public static string DealerSaved {
            get {
                return ResourceManager.GetString("DealerSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer updated successfully..
        /// </summary>
        public static string DealerUpdated {
            get {
                return ResourceManager.GetString("DealerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee deleted successfully..
        /// </summary>
        public static string EmployeeDeleted {
            get {
                return ResourceManager.GetString("EmployeeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee already exists!.
        /// </summary>
        public static string EmployeeExists {
            get {
                return ResourceManager.GetString("EmployeeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee saved successfully..
        /// </summary>
        public static string EmployeeSaved {
            get {
                return ResourceManager.GetString("EmployeeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee updated successfully..
        /// </summary>
        public static string EmployeeUpdated {
            get {
                return ResourceManager.GetString("EmployeeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploaded successfully..
        /// </summary>
        public static string ImageUploaded {
            get {
                return ResourceManager.GetString("ImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect!.
        /// </summary>
        public static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted successfully..
        /// </summary>
        public static string ProductDeleted {
            get {
                return ResourceManager.GetString("ProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product saved successfully..
        /// </summary>
        public static string ProductSaved {
            get {
                return ResourceManager.GetString("ProductSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product updated successfully..
        /// </summary>
        public static string ProductUpdated {
            get {
                return ResourceManager.GetString("ProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating saved successfully..
        /// </summary>
        public static string RatingCreated {
            get {
                return ResourceManager.GetString("RatingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating deleted successfully..
        /// </summary>
        public static string RatingDeleted {
            get {
                return ResourceManager.GetString("RatingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings fetched successfully..
        /// </summary>
        public static string RatingFecthed {
            get {
                return ResourceManager.GetString("RatingFecthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating updated successfully..
        /// </summary>
        public static string RatingUpdated {
            get {
                return ResourceManager.GetString("RatingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists!.
        /// </summary>
        public static string RoleExists {
            get {
                return ResourceManager.GetString("RoleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role created successfully..
        /// </summary>
        public static string RoleSaved {
            get {
                return ResourceManager.GetString("RoleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles fetched successfully..
        /// </summary>
        public static string RolesFetched {
            get {
                return ResourceManager.GetString("RolesFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Shape deleted successfully..
        /// </summary>
        public static string StoneShapeDeleted {
            get {
                return ResourceManager.GetString("StoneShapeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Shape already exists..
        /// </summary>
        public static string StoneShapeExists {
            get {
                return ResourceManager.GetString("StoneShapeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Shape created successfully..
        /// </summary>
        public static string StoneShapeSaved {
            get {
                return ResourceManager.GetString("StoneShapeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Shape updated successfully..
        /// </summary>
        public static string StoneShapeUpdated {
            get {
                return ResourceManager.GetString("StoneShapeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users fetched successfully..
        /// </summary>
        public static string UserFetched {
            get {
                return ResourceManager.GetString("UserFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User rating saved successfully..
        /// </summary>
        public static string UserRatingSaved {
            get {
                return ResourceManager.GetString("UserRatingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved successfully..
        /// </summary>
        public static string UserSaved {
            get {
                return ResourceManager.GetString("UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video uploaded successfully..
        /// </summary>
        public static string VideoUploaded {
            get {
                return ResourceManager.GetString("VideoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
    }
}
