//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.CommonUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.CommonUtility.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fetched successfully..
        /// </summary>
        public static string DataFetched {
            get {
                return ResourceManager.GetString("DataFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploaded successfully..
        /// </summary>
        public static string ImageUploaded {
            get {
                return ResourceManager.GetString("ImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect!.
        /// </summary>
        public static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating saved successfully..
        /// </summary>
        public static string RatingCreated {
            get {
                return ResourceManager.GetString("RatingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating deleted successfully..
        /// </summary>
        public static string RatingDeleted {
            get {
                return ResourceManager.GetString("RatingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings fetched successfully..
        /// </summary>
        public static string RatingFecthed {
            get {
                return ResourceManager.GetString("RatingFecthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating updated successfully..
        /// </summary>
        public static string RatingUpdated {
            get {
                return ResourceManager.GetString("RatingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role created successfully..
        /// </summary>
        public static string RoleSaved {
            get {
                return ResourceManager.GetString("RoleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles fetched successfully..
        /// </summary>
        public static string RolesFetched {
            get {
                return ResourceManager.GetString("RolesFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users fetched successfully..
        /// </summary>
        public static string UserFetched {
            get {
                return ResourceManager.GetString("UserFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User rating saved successfully..
        /// </summary>
        public static string UserRatingSaved {
            get {
                return ResourceManager.GetString("UserRatingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved successfully..
        /// </summary>
        public static string UserSaved {
            get {
                return ResourceManager.GetString("UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video uploaded successfully..
        /// </summary>
        public static string VideoUploaded {
            get {
                return ResourceManager.GetString("VideoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
    }
}
